### PR TITLE
Fix object rename not updating the tree store

### LINKED ISSUE #203: [Bug] Event pimcore.events.prepareAffectedNodes details not correctly built after renaming assets or data objects
### Version

1.0 - 1.x

### Steps to reproduce

Pretty hard to without a custom tree, but should be available with an internal feature

### Actual Behavior

After renaming an asset or an data object in the custom tree, the renamed element is marked as dirty even though it is updated in the standard tree correctly

image

Another Problem is, if you try to rename the element again, the old value will show up

### Expected Behavior

Event pimcore.events.prepareAffectedNodes is built correctly and the field is not marked as dirty anymore and updated accordingly as it works for the documents.

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #203

### CODE REVIEW

**Comment by robertSt7** [comment]
@dvesh3 We have the same problem with assets.

**Comment by dvesh3** [comment]
> @dvesh3 We have the same problem with assets.

@robertSt7 fixed it for assets and documents tree. Also reverted the approach for reloading parent on document tree rename.

File: src/Controller/Admin/Document/DocumentController.php [hunk 1]
```diff
@@ -522,15 +530,19 @@ public function updateAction(Request $request): JsonResponse
...
                     if ($oldPath && $oldPath != $document->getRealFullPath()) {
                         $this->firePostMoveEvent($document, $oldDocument, $oldPath);
                     }
                 } catch (Exception $e) {
                     return $this->adminJson(['success' => false, 'message' => $e->getMessage()]);
                 }
             } else {
-                $msg = 'Prevented moving document, because document with same path+key already exists or the document is locked. ID: ' . $document->getId();
+                $msg = 'prevented moving document, because document with same path+key already exists';
+                $msg .= ' aor the document is locked. ID: ' . $document->getId();
```
Comment (robertSt7) [inline src/Controller/Admin/Document/DocumentController.php]:
```suggestion
                $msg = 'prevented moving document, because document with same path+key already exists' .
                    ' or the document is locked. ID: ' . $document->getId();
```

**Review by robertSt7 — CHANGES_REQUESTED** [review]
@divesh For me the error still occurs with Assets and Documents. Could you please take a second look? Thanks

**Comment by dvesh3** [comment]
> For me the error still occurs with Assets and Documents. Could you please take a second look? Thanks

@robertSt7 yes, there were extra checks in editCompleteKey to check if the element is open before performing reopenelement and these checks are already performed in the called method so removed it.

Note: better compare differences with `/files?diff=split&w=1`
