### PR TITLE
[Bug]: Removes `Filter by relation` from reverse object relation grid view

### LINKED ISSUE #16273: [Bug, EC]: Grid View filtering: No results using reverse object relations on M2M relations
### Pimcore version

11

### Steps to reproduce

Using Pimcore demo:

- Open grid view for Data Objects/Product Data/Categories
- Add 'Cars' relation to selected grid columns
- Apply
- Select 'Filter by relations' at 'Cars' column head
- Select 'Search objects'
- Select object '/Product Data/Cars/citroen/2CV'
- Apply filter

### Actual Behavior

Existing relation isn't displayed. 

### Expected Behavior

Existing relations should be displayed, too.

### PR DESCRIPTION
**Pull request by kingjia90**
Resolves https://github.com/pimcore/pimcore/issues/16273#issuecomment-1863949815

Removing due to being not supported yet.

The check is on if this function `getRelationFilter` exists
https://github.com/pimcore/admin-ui-classic-bundle/blob/5f9a715c64b8f3e033523b3d07b99930a1689ea2/public/js/pimcore/element/helpers/gridColumnConfig.js#L355

### CODE REVIEW

File: public/js/pimcore/object/tags/reverseObjectRelation.js [hunk 1]
```diff
@@ -19,6 +19,12 @@ pimcore.object.tags.reverseObjectRelation = Class.create(pimcore.object.tags.man
 
     pathProperty: "fullpath",
 
+    getGridColumnConfig: function ($super, fieldConfig) {
+        let gridColumnConfig = $super(fieldConfig);
```
Comment (robertSt7) [inline public/js/pimcore/object/tags/reverseObjectRelation.js]:
```suggestion
        const gridColumnConfig = $super(fieldConfig);
```
