### PR TITLE
Handle pimcore.helpers.download exceptions

### LINKED ISSUE #126: Handle pimcore.helpers.download exceptions
At the moment, exceptions are thrown e.g. `createNotFoundException` and not handled in js.

this one tricky to reproduce with default scenarios so it needs a bit of a tweaking:
 - tweak a controller action (for downloading) to return `createNotFoundException` e.g. AssetController::downloadAction
 - Open asset image and click download.
 - the request will be redirected to 404 page instead of handling it gracefully in admin UI.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #126

### CODE REVIEW

File: public/js/pimcore/helpers.js [hunk 1]
```diff
@@ -876,7 +876,21 @@ pimcore.helpers.download = function (url) {
...
+    }
+    iframe.src = url;
+
+    document.getElementById('download_helper_iframe').onload = function() {
+        if(iframe.src !== 'about:blank') {
+            const title = iframe.contentDocument.title;
+            pimcore.helpers.showNotification(t('error'), title, 'error');
+            iframe.src = 'about:blank';
+        }
+    }
```
Comment (kingjia90) [inline public/js/pimcore/helpers.js]:
```suggestion
    iframe.onload = function() {
          const title = iframe.contentDocument.title;
          pimcore.helpers.showNotification(t('error'), title, 'error');
          iframe.src = 'about:blank';
    }
```
this may doing the trick in a simpler way.
When the download is triggered, there's no DOM `onload` event at all

Comment (kingjia90) [reply public/js/pimcore/helpers.js]: let's also add a js comment on the purpose of this `iframe`
